# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-10 05:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(default=uuid.uuid4, editable=False, max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('room_number', models.IntegerField()),
                ('isCurrentPatient', models.BooleanField(default=True)),
                ('patientCheckedOutDate', models.DateField(blank=True, null=True)),
                ('hospital_name', models.CharField(choices=[('UH', 'Unvirsity Hospitals'), ('CC', 'Cleveland Clinic')], default='UH', max_length=2)),
                ('relation', models.CharField(choices=[('mother', 'mother'), ('father', 'father'), ('brother', 'brother'), ('sister', 'sister'), ('friend', 'friend')], default='friend', max_length=30)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MediaDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('hasBeenViewed', models.BooleanField(default=False)),
                ('uploader', models.CharField(max_length=40)),
                ('benefactor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geri_app.Benefactor')),
            ],
        ),
    ]
