# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geri_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefactor',
            name='hospital_name',
            field=models.CharField(choices=[('UH', 'Unvirsity Hospitals'), ('CC', 'Cleveland Clinic')], default='UH', max_length=2),
        ),
        migrations.AddField(
            model_name='benefactor',
            name='room_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
