# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geri_app', '0002_auto_20170402_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefactor',
            name='isCurrentPatient',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='benefactor',
            name='patientCheckedOutDate',
            field=models.DateField(default=None, editable=False),
        ),
    ]
