# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geri_app', '0005_auto_20170411_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefactor',
            name='isCurrentPatient',
            field=models.BooleanField(default=True),
        ),
    ]
