# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geri_app', '0006_auto_20170422_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediadocument',
            name='benefactor_id',
        ),
    ]
