# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geri_app', '0007_remove_mediadocument_benefactor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediadocument',
            name='benefactor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geri_app.Benefactor'),
        ),
    ]
