# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-24 01:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geri_app', '0010_auto_20170519_0610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediadocument',
            old_name='benefactor_id',
            new_name='benefactor',
        ),
    ]
