# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-19 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geri_app', '0011_auto_20170524_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefactor',
            name='relation',
            field=models.CharField(choices=[('mother', 'mother'), ('father', 'father'), ('brother', 'brother'), ('sister', 'sister'), ('friend', 'friend')], default='friend', max_length=30),
        ),
    ]
